spring.application.name=Swiggy
spring.datasource.url=jdbc:mysql://localhost:3306/swiggy?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=root

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.sql.init.mode=always
spring.sql.init.data-locations=classpath:schema.sql,classpath:data.sql
spring.jpa.defer-datasource-initialization=true
server.port=8085
